/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assignment.courserecoverysystem.view;

import javax.swing.JOptionPane;
import com.assignment.courserecoverysystem.controller.AuthController;
/**
 *
 * @author User
 */
public class ResetPasswordForm extends javax.swing.JFrame {

    
private String email;
    /**
     * Creates new form ResetPasswordForm
     */
    public ResetPasswordForm(String email) {
        initComponents();
        this.email = email;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PwdTF = new javax.swing.JPasswordField();
        ConfirmPwdTF = new javax.swing.JPasswordField();
        ResetPwdBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Password: ");

        jLabel2.setText("Confirm Password:");

        PwdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PwdTFActionPerformed(evt);
            }
        });

        ResetPwdBtn.setText("Reset Password");
        ResetPwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPwdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(143, 143, 143))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(100, 100, 100))
                            .addComponent(PwdTF)
                            .addComponent(ConfirmPwdTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(ResetPwdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(PwdTF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPwdTF)
                .addGap(18, 18, 18)
                .addComponent(ResetPwdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetPwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPwdBtnActionPerformed
        String newPwd = new String(PwdTF.getPassword()).trim();
        String confirmPwd = new String(ConfirmPwdTF.getPassword()).trim();
        
        // DEBUG – see what we really read
        System.out.println("DEBUG newPwd    = '" + newPwd + "'");
        System.out.println("DEBUG confirmPwd= '" + confirmPwd + "'");
        System.out.println("DEBUG email     = '" + email + "'");   // email variable in this form

        // step 1: Check empty
        if (newPwd.isEmpty() || confirmPwd.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in both password fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //step 2: check same
        if(!newPwd.equals(confirmPwd)){
            JOptionPane.showConfirmDialog(this, "New password and confirm password do not match.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
        //step 3: validation
        if(newPwd.length() < 8){
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // must contain at least one uppercase letter
        if (!newPwd.matches(".*[A-Z].*")) {
            JOptionPane.showMessageDialog(this,
                    "Password must contain at least one uppercase letter (A-Z).",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // must contain at least one lowercase letter
        if (!newPwd.matches(".*[a-z].*")) {
            JOptionPane.showMessageDialog(this,
                    "Password must contain at least one lowercase letter (a-z).",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // must contain at least one symbol
        if (!newPwd.matches(".*[!@#$%^&*(),.?\":{}|<>].*")) {
            JOptionPane.showMessageDialog(this,
                    "Password must contain at least one symbol (e.g. !, @, #, $).",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // step 4: call controller to update user.txt
        boolean success = AuthController.resetPassword(email, newPwd);
        
        if(success){
            JOptionPane.showMessageDialog(this, "Reset password successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            new LoginForm().setVisible(true);
        } else{
            JOptionPane.showMessageDialog(this, "Failed to reset password. User not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_ResetPwdBtnActionPerformed

    private void PwdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PwdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PwdTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPwdTF;
    private javax.swing.JPasswordField PwdTF;
    private javax.swing.JButton ResetPwdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
