/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package courserecoverysystem.view.login;

import courserecoverysystem.LoginScreen;
import java.awt.Color;
import courserecoverysystem.service.AuthService;
import courserecoverysystem.model.User;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(78, 118, 163));
        this.setLocationRelativeTo(null); //auto set centre screen
        // Placeholder text
        EmailTF.setText("example@university.edu");
        EmailTF.setForeground(Color.GRAY); // make it look like a hint

        // When the user clicks (focus gained)
        EmailTF.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (EmailTF.getText().equals("example@university.edu")) {
                    EmailTF.setText("");
                    EmailTF.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (EmailTF.getText().isEmpty()) {
                    EmailTF.setForeground(Color.GRAY);
                    EmailTF.setText("example@university.edu");
                }
            }
        });
        
        // --- Password placeholder ---
        PwdTF.setEchoChar((char)0);  // disable hiding bullets
        PwdTF.setText("Password");
        PwdTF.setForeground(Color.GRAY);

        // Add focus listener
        PwdTF.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                String passwordText = String.valueOf(PwdTF.getPassword());
                if (passwordText.equals("Password")) {
                    PwdTF.setText("");
                    PwdTF.setForeground(Color.BLACK);
                    PwdTF.setEchoChar('•');  // enable hiding when typing
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                String passwordText = String.valueOf(PwdTF.getPassword());
                if (passwordText.isEmpty()) {
                    PwdTF.setEchoChar((char)0); // disable hiding again
                    PwdTF.setText("Password");
                    PwdTF.setForeground(Color.GRAY);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new courserecoverysystem.uiElements.RoundedPanel();
        LoginLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();
        PwdLabel = new javax.swing.JLabel();
        PwdTF = new javax.swing.JPasswordField();
        ForgotPwdLabel = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(78, 118, 163));
        setResizable(false);

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("LOG IN");
        LoginLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLabel.setText("Email:");

        PwdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PwdLabel.setText("Password: ");

        ForgotPwdLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ForgotPwdLabel.setForeground(new java.awt.Color(0, 102, 204));
        ForgotPwdLabel.setText("Forgot Password?");
        ForgotPwdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotPwdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPwdLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgotPwdLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgotPwdLabelMouseExited(evt);
            }
        });

        LoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("APU Course Recovery System");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PwdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PwdTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailTF)
                            .addComponent(ForgotPwdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoginBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(419, 419, 419))))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PwdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PwdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ForgotPwdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(111, 111, 111))
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pfp/Small Logo.png"))); // NOI18N
        jLabel1.setText("<html>Course Recovery System <p> <font size=3>Asia Pacific University</font></p> </html>");
        jLabel1.setIconTextGap(10);
        jLabel1.setMaximumSize(new java.awt.Dimension(541, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(541, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(541, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForgotPwdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPwdLabelMouseClicked
        ForgotPasswordForm forgot = new ForgotPasswordForm();
        this.dispose();
        forgot.setVisible(true);
    }//GEN-LAST:event_ForgotPwdLabelMouseClicked

    private void ForgotPwdLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPwdLabelMouseEntered
        ForgotPwdLabel.setText("<html><u>Forgot Password?</u></html>");
    }//GEN-LAST:event_ForgotPwdLabelMouseEntered

    private void ForgotPwdLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPwdLabelMouseExited
        ForgotPwdLabel.setText("Forgot Password?");        
    }//GEN-LAST:event_ForgotPwdLabelMouseExited

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String email = EmailTF.getText();
        String password = new String(PwdTF.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter email and password!");
            return;
        }

        AuthService authService = new AuthService();
        boolean isValid = authService.validateCredentials(email, password);

        if (isValid) {
            JOptionPane.showMessageDialog(this, "Login Successful!");
            User currentUser = User.getCurrentUser();  
            String role = currentUser.getRole().toLowerCase();

            switch (role) {
                case "lecturer" -> {
                    LoginScreen.SwapToLecturer();
                    LoginScreen.showContent("lhome");
                    this.dispose();
                }
                case "officer" -> {
                    LoginScreen.SwapToOfficer();
                    LoginScreen.showContent("ohome");
                    this.dispose();
                }
                case "admin" -> {
                    LoginScreen.SwapToAdmin();
                    LoginScreen.showContent("ahome");
                    this.dispose();
                }
                case "student" -> {
                    LoginScreen.SwapToStudent();
                    LoginScreen.showContent("shome");
                    this.dispose();
                }
                    
                default -> JOptionPane.showMessageDialog(this, "Unsupported role: " + role);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid credentials. Please try again.");
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JLabel ForgotPwdLabel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel PwdLabel;
    private javax.swing.JPasswordField PwdTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private courserecoverysystem.uiElements.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
